### ISSUE TITLE
remote: Permission to g-simmons/infovisfinal.git denied to kchapinriddle

### ISSUE THREAD

**Issue by kchapinriddle** [g-simmons/infovisfinal#4]
I can't push.  Error message is
remote: Permission to g-simmons/infovisfinal.git denied to kchapinriddle.

**Comment by g-simmons** [comment]
On my end it looks like you haven't accepted the invite to the repo. Maybe check the email invite and click the link again if it didn't work the first time.

![image](https://user-images.githubusercontent.com/28633482/54090162-71e68480-432e-11e9-9d27-53bdfd9421c3.png)
